sc_proj/sc_app/urls.py
from django.urls import path
from sc_app import views

app_name = 'sc_app'

urlpatterns = [
    path('data/', views.data, name='data'),
    path('paper/', views.paper, name='paper'),
    path('people/', views.people, name='people')
]

sc_proj/sc_proj/urls.py
from django.contrib import admin
from django.urls import path, include
from sc_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('sc_app/', include('sc_app.urls'))
]

sc_proj/sc_app/models.py
from django.db import models

# Create your models here.
class Colors(models.Model):

    brand = models.TextField(max_length=100, primary_key=True)
    hex = models.CharField(max_length=7, unique=True)

    class Meta:

        verbose_name_plural = 'Colors'

    def __str__(self):
        return self.brand

class Info(models.Model):

    sg_id = models.TextField(max_length=50, primary_key=True)
    address = models.CharField(max_length=250)
    name = models.ForeignKey(Colors,
                            on_delete=models.CASCADE,
                            related_name='+')
    lat = models.FloatField()
    lon = models.FloatField()
    sq_ft = models.FloatField()
    p_lot = models.BooleanField()
    category = models.CharField(max_length=100)

    class Meta:

        verbose_name_plural = 'Info'

    def __str__(self):

        return self.sg_id

class Closed(models.Model):

    name = models.TextField(max_length=3, primary_key=True)
    id = models.ForeignKey(Info,
                            on_delete=models.CASCADE,
                            related_name='+')

    class Meta:

        verbose_name_plural = 'Closed'

    def __str__(self):

        return self.name

class Movement(models.Model):

    id = models.AutoField(primary_key=True)
    open_store = models.ForeignKey(Info,
                                on_delete=models.CASCADE,
                                related_name="+")
    closed_store = models.ForeignKey(Info,
                                on_delete=models.CASCADE,
                                related_name='+')
    movement = models.FloatField()
    yr = models.IntegerField(default=0)


    def __str__(self):

        return(str(self.id))


class Cbgs(models.Model):

    cbgID = models.IntegerField(primary_key=True, null=False)
    population = models.IntegerField()
    median_income = models.FloatField()

    class Meta:

        verbose_name_plural = 'CBGs'


    def __str__(self):

        return(str(self.cbgID))


class CbgStore(models.Model):

    ID = models.AutoField(primary_key=True)
    cbgID = models.ForeignKey(Cbgs,
                            on_delete = models.CASCADE,
                            related_name = "+")
    storeID = models.ForeignKey(Info,
                            on_delete = models.CASCADE,
                            related_name = "+")
    percent_visit = models.FloatField()
    number_visits = models.IntegerField()
    pop_near_store = models.FloatField()
    dist_store_cbg = models.FloatField()
    store_area = models.IntegerField()
    p_lot = models.BooleanField()
    poi_near_store = models.IntegerField()
    diversity_near_store = models.FloatField()
    demo_similarity = models.FloatField()
    med_inc_near_store = models.FloatField()
    brand = models.CharField(max_length= 80)
    num_visit_brand = models.IntegerField()
    percent_visit_brand = models.FloatField()
    year = models.IntegerField()

    def __str__(self):

        return('Connection: ' + str(self.ID))

sc_proj/sc_app/forms.py
from django import forms
from sc_app.models import Closed

class YearSelect(forms.Form):
    year = forms.ChoiceField(choices=((2018,'2018'),(2019,'2019')), label="Select a year")


class CloseStore(forms.Form):

    store = forms.ModelChoiceField(Closed.objects.order_by('name'), empty_label='',to_field_name='name', label='Select a Store')
    year = forms.ChoiceField(choices=((2018,'2018'),(2019,'2019')), label="Select a year")
    type = forms.ChoiceField(choices=(("foot",'Foot Traffic'),('cbg','Census Blocks')), label="Select Data")

sc_proj/sc_app/views.py
from django.shortcuts import render
from django.db import connection
from . import forms
from sc_app.models import Closed, Colors, Movement, Info, Cbgs, CbgStore
import plotly.graph_objs as go
from plotly.offline import plot
import json
import pandas as pd
from plotly.subplots import make_subplots
from sc_proj.config import *

colors = pd.read_csv('static/csv/brand_colors.csv',index_col=0)
colorDict = {x:y for x,y in zip(colors.brands, colors.colors)}

###############################
##         INDEX VIEW         ##
###############################

# Create your views here.
def index(request):
    return render(request, 'sc_app/index.html')


























# ###############################
# ##     TOPSTORES VIEW        ##
# ###############################
#
#
# def topStores(request):
#     form = forms.YearSelect()
#
#     ###############################
#     ##    Generate base plot     ##
#     ###############################
#     mapbox_access_token = get_mb_token()
#     MB_style = 'mapbox://styles/mapbox/streets-v11'
#     plot_divs = []
#     table_dicts = []
#
#     for store in ['T07','T06','T11']:
#         year = 2018
#         store = Closed.objects.filter(name=store)
#         store_name = [str(x.name) for x in store][0]
#         store = [str(x.id) for x in store][0]
#
#
#         qs = Movement.objects.select_related().filter(closed_store=store, yr=year)
#         q = qs.values('open_store', 'movement')
#         closed = pd.DataFrame.from_records(q)
#
#         closed = closed.rename(columns={'open_store':'sg_id'})
#         closed.set_index('sg_id', inplace=True)
#         closed = closed.drop(index=store)
#         mv_min = closed['movement'].min()
#         mv_max = closed['movement'].max()
#         mv_range = mv_max-mv_min
#         closed['norm'] = closed['movement'].apply(lambda x: 5+((x - mv_min)*(100-5))/mv_range)
#
#
#         query = Info.objects.filter(sg_id = store)
#
#         center = [(x.lat, x.lon) for x in query][0]
#
#         fig = go.Figure()
#
#         cols = Colors.objects.all()
#         for col in cols:
#
#             color = str(col.hex)
#             brand = str(col.brand)
#
#             qs = Info.objects.filter(name = brand)
#             q = qs.values('sg_id','address','lat','lon','category','sq_ft','p_lot')
#             df = pd.DataFrame.from_records(q)
#             closed = closed.rename(columns={'open_store':'sg_id'})
#             df.set_index('sg_id', inplace=True)
#             plot_df = df.join(closed, on='sg_id',how='left')
#             plot_df['movement'] = plot_df['movement'].astype(str)
#             plot_df['sq_ft'] = plot_df['sq_ft'].astype(str)
#             plot_df['p_lot'] = plot_df['p_lot'].astype(str)
#             plot_df.dropna(inplace=True)
#
#             fig.add_trace(go.Scattermapbox(
#                                 lat = plot_df.lat,
#                                 lon = plot_df.lon,
#                                 mode = 'markers',
#                                 marker = go.scattermapbox.Marker(
#                                             size=plot_df.norm,
#                                             color=color,
#                                             opacity=0.6
#                                 ),
#                                 name = brand,
#                                 hovertemplate = '<b>'+ brand + '</b><br><br>'
#                                                 '<b>Additional Traffic: </b><br>' + plot_df.movement + '<br>' +
#                                                 '<b>Address: </b><br>' + plot_df.address + '<br>' +
#                                                 '<b>Category: </b><br>' + plot_df.category + '<br>' +
#                                                 '<b>Square Footage: </b><br>' + plot_df.sq_ft + '<br>' +
#                                                 '<b>Has Parking Lot: </b><br>' + plot_df.p_lot + '<br>' +
#                                                 "<extra></extra>"
#
#
#                             ))
#
#         qs = Info.objects.select_related().filter(sg_id=store)
#         q = qs.values('sg_id','address','lat','lon','category','sq_ft','p_lot')
#         ct_info = pd.DataFrame.from_records(q)
#         ct_info['sq_ft'] = ct_info['sq_ft'].astype(str)
#         ct_info['p_lot'] = ct_info['p_lot'].astype(str)
#
#         fig.add_trace(go.Scattermapbox(
#                             lat = [center[0]],
#                             lon = [center[1]],
#                             mode = 'markers',
#                             marker=go.scattermapbox.Marker(
#                                         size = 10,
#                                         color = '#000000',
#                                         opacity = 1
#                             ),
#                             name = 'Target '+store_name+' **closed**',
#                             hovertemplate = '<b>Target '+store_name+' **closed**</b><br><br>'
#                                             '<b>Address: </b><br>' + ct_info.address + '<br>' +
#                                             '<b>Category: </b><br>' + ct_info.category + '<br>' +
#                                             '<b>Square Footage: </b><br>' + ct_info.sq_ft + '<br>' +
#                                             '<b>Has Parking Lot: </b><br>' + ct_info.p_lot + '<br>' +
#                                             "<extra></extra>"
#         ))
#
#         fig.update_layout(
#             autosize=False,
#             hovermode='closest',
#             showlegend=False,
#             margin=dict(
#                 l=0,
#                 r=0,
#                 t=30,
#                 b=20),
#             mapbox=dict(
#                 accesstoken=mapbox_access_token,
#                 bearing=0,
#                 center=dict(
#                     lat=center[0],
#                     lon=center[1]),
#                 pitch=60,
#                 zoom=10),
#             title = "Resulting Movement After Closing Store " + store_name,
#             height=500,
#             width=500
#         )
#
#
#         qs = Info.objects.exclude(sg_id=store)
#         q = qs.values('sg_id','name','address','lat','lon','category','sq_ft','p_lot')
#         df = pd.DataFrame.from_records(q)
#         df.set_index('sg_id', inplace=True)
#
#         tdf = df.join(closed)
#         top_tdf = tdf.sort_values(by='movement', ascending=False).head(5)
#         table_dicts.append([{'brand':top_tdf.loc[i,'name'],
#                         'address':top_tdf.loc[i,'address'],
#                         'sq_ft':top_tdf.loc[i,'sq_ft'],
#                         'move':round(top_tdf.loc[i,'movement'])} for i in list(top_tdf.index)])
#
#
#         plot_divs.append(plot(fig, output_type='div', include_plotlyjs=False))
#
#
#     ###############################
#     ##  Generate plot from input ##
#     ###############################
#
#     if request.method == 'POST':
#         form = forms.YearSelect(request.POST)
#
#         if form.is_valid():
#
#             ###############################
#             ##   Bubble plot of movement ##
#             ###############################
#             for store in ['T07','T11','T06']:
#
#                 year = form.cleaned_data['year']
#                 store = Closed.objects.filter(name=store)
#                 store_name = [str(x.name) for x in store][0]
#                 store = [str(x.id) for x in store][0]
#
#
#                 qs = Movement.objects.select_related().filter(closed_store=store, yr=year)
#                 q = qs.values('open_store', 'movement')
#                 closed = pd.DataFrame.from_records(q)
#
#                 closed = closed.rename(columns={'open_store':'sg_id'})
#                 closed.set_index('sg_id', inplace=True)
#                 closed = closed.drop(index=store)
#                 mv_min = closed['movement'].min()
#                 mv_max = closed['movement'].max()
#                 mv_range = mv_max-mv_min
#                 closed['norm'] = closed['movement'].apply(lambda x: 5+((x - mv_min)*(100-5))/mv_range)
#
#
#                 query = Info.objects.filter(sg_id = store)
#
#                 center = [(x.lat, x.lon) for x in query][0]
#
#                 fig = go.Figure()
#
#                 cols = Colors.objects.all()
#                 for col in cols:
#
#                     color = str(col.hex)
#                     brand = str(col.brand)
#
#                     qs = Info.objects.filter(name = brand)
#                     q = qs.values('sg_id','address','lat','lon','category','sq_ft','p_lot')
#                     df = pd.DataFrame.from_records(q)
#                     closed = closed.rename(columns={'open_store':'sg_id'})
#                     df.set_index('sg_id', inplace=True)
#                     plot_df = df.join(closed, on='sg_id',how='left')
#                     plot_df['movement'] = plot_df['movement'].astype(str)
#                     plot_df['sq_ft'] = plot_df['sq_ft'].astype(str)
#                     plot_df['p_lot'] = plot_df['p_lot'].astype(str)
#                     plot_df.dropna(inplace=True)
#
#                     fig.add_trace(go.Scattermapbox(
#                                         lat = plot_df.lat,
#                                         lon = plot_df.lon,
#                                         mode = 'markers',
#                                         marker = go.scattermapbox.Marker(
#                                                     size=plot_df.norm,
#                                                     color=color,
#                                                     opacity=0.6
#                                         ),
#                                         name = brand,
#                                         hovertemplate = '<b>'+ brand + '</b><br><br>'
#                                                         '<b>Additional Traffic: </b><br>' + plot_df.movement + '<br>' +

sc_proj/templates/sc_app/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <title>Store Closure</title>
    <link rel="icon" href="{% static 'images/favicon.ico' %}">
    <meta charset="utf-8">
    <!-- Latest compiled and minified CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static "css/style.css" %}">
    {% block head_block %}
    {% endblock %}
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container">
        <a class="navbar-brand" href="{% url "index" %}">
          <img src="{% static 'images/Nav_logo.png' %}" alt="" width="90px" height="50px" class="d-inline-block align-top">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" aria-current="page" href="{% url "sc_app:paper" %}">The Paper</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url "sc_app:data" %}">The Data</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url "sc_app:people" %}">The People</a>
            </li>
        </div>
      </div>
    </nav>

    <div class="container">
      <div class="row">
        <div class="col-2">
              {% block sidebar_block %}
              {% endblock %}
        </div>
        <div id='main' class="col-10">
              {% block body_block %}
              {% endblock %}
        </div>
      </div>
    </div>

  </body>
  <footer class="container py-5">
    <div class="row">
      <div class="col-12 col-md">
        <img src="{% static 'images/mini_logo_sm.png' %}" height=24 width=24 alt="logo">
        <small class="d-block mb-3 text-muted">&copy; 2021</small>
      </div>
      <div class="col-6 col-md">
        <h5>Resources</h5>
        <ul class="list-unstyled text-small">
          <li><a class="link-secondary" href="{% url 'sc_app:paper' %}">The Paper</a></li>
          <li><a class="link-secondary" href="{% url 'sc_app:data' %}">The Data</a></li>
        </ul>
      </div>
      <div class="col-6 col-md">
        <h5>About</h5>
        <ul class="list-unstyled text-small">
          <li><a class="link-secondary" href="{% url 'sc_app:people'%}">Team</a></li>
          <li><a class="link-secondary" href="https://www.media.mit.edu/about/overview/">MIT Media Lab</a></li>
        </ul>
      </div>
      <div class="col-6 col-md">
      </div>
      <div class="col-6 col-md">
      </div>
    </div>
  </footer>
</html>

sc_proj/templates/sc_app/base_fw.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <title>Store Closure</title>
    <link rel="icon" href="{% static 'images/favicon.ico' %}">
    <meta charset="utf-8">
    <!-- Latest compiled and minified CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% block head_block %}
    {% endblock %}
  </head>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <a class="navbar-brand" href="{% url "index" %}">
      <img src="{% static 'images/Nav_logo.png' %}" alt="" width="90px" height="50px" class="d-inline-block align-top">
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url "sc_app:paper" %}">The Paper</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url "sc_app:data" %}">The Data</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url "sc_app:people" %}">The People</a>
        </li>
    </div>
  </div>
</nav>


  <body>
    <div class="container">
      {% block body_block %}
      {% endblock %}
    </div>
  </body>
  <footer class="container py-5">
    <div class="row">
      <div class="col-12 col-md">
        <img src="{% static 'images/mini_logo_sm.png' %}" height=24 width=24 alt="logo">
        <small class="d-block mb-3 text-muted">&copy; 2021</small>
      </div>
      <div class="col-6 col-md">
        <h5>Resources</h5>
        <ul class="list-unstyled text-small">
          <li><a class="link-secondary" href="{% url 'sc_app:paper' %}">The Paper</a></li>
          <li><a class="link-secondary" href="{% url 'sc_app:data' %}">The Data</a></li>
        </ul>
      </div>
      <div class="col-6 col-md">
        <h5>About</h5>
        <ul class="list-unstyled text-small">
          <li><a class="link-secondary" href="{% url 'sc_app:people'%}">Team</a></li>
          <li><a class="link-secondary" href="https://www.media.mit.edu/about/overview/">MIT Media Lab</a></li>
        </ul>
      </div>
      <div class="col-6 col-md">
      </div>
      <div class="col-6 col-md">
      </div>
    </div>
  </footer>
</html>

sc_proj/templates/sc_app/dataBU.html
<!DOCTYPE html>
{% extends 'sc_app/base.html' %}

{% block head_block %}

<script src="https://cdn.plot.ly/plotly-latest.min.js"></script>

{% endblock %}

{% block sidebar_block %}

<h1>Close a Store:</h1>
<form method="POST">
  {{ form.as_p }}
  {% csrf_token %}
  <input type="submit" class="btn btn-primary" value="Submit">
</form>

{% endblock %}

{% block body_block %}
<div class='row md-12'>
    {{ store_plot|safe }}
</div>
<div class='row md-12'>
  {% if store_bar %}
    {{ store_bar|safe }}
  {% else %}
  {% endif %}
</div>
<div class='row md-12'>
    {{ choro_plot|safe }}
</div>
<div class='row md-12'>
  {% if cbg_bar %}
    {{ cbg_bar|safe }}
  {% else %}
  {% endif %}
</div>


<hr class="featurette-divider">
<h4>Top 5 Benefactors</h4>
  {% if tbl %}
  <div class='table-reponsive'>
    <table class="table table-striped">
      <thead>
        <th scope="col">Brand</th>
        <th scope="col">Category</th>
        <th scope="col">Address</th>
        <th scope="col">Square Footage</th>
        <th scope="col">Additional Traffic</th>
      </thead>
      {% for row in tbl %}
      <tr>
        <td>{{ row.brand }}</td>
        <td>{{ row.category }}</td>
        <td>{{ row.address }}</td>
        <td>{{ row.sq_ft }}</td>
        <td>{{ row.move }}</td>
      </tr>
    {% endfor %}
    </table>
    {% else %}
      <p>Select a Store.</p>
    {% endif %}
  </div>
{% endblock %}

sc_proj/templates/sc_app/index.html
<!DOCTYPE html>
{% extends 'sc_app/base_fw.html' %}
{% load static %}

{% block head_block %}
{% endblock %}


{% block body_block %}
<div id="banner">
  <div class="position-relative overflow-hidden p-3 p-md-5 m-md-3 text-center bg-transparent">
    <div id="heading" class="col-md-5 p-lg-8 mx-auto my-5">
      <h1 class="display-6 fw-normal">Choosing a Target Location to Close</h1>
      <p class="lead fw-normal">Reverse engineering a gravity model to predict optimally effective store closures.</p>
      <a class="btn btn-outline-secondary" href="{% url "sc_app:data"%}">Explore the data</a>
    </div>
  </div>
</div>
<br>
<div class='container-fluid'>
  <div class="row">
    <div class="col-2">
      <div class="potition-fluid text-center">
        <img class="mt-3 mb-3" src="{% static 'images/Target_Corporation_logo.png' %}" width='100px' height='100px'>
        <img class="mt-3 mb-3" src="{% static 'images/SG_logo_tall.png' %}" width="100px" height="59px">
      </div>
    </div>
    <div class="col-8">
      <h2>The  Premise</h2>
      <br>
      <p>No business wishes to lose revenue to its competitors, so the decision can be extremely difficult if they are forced to close one of several locations due to downsizing or unforeseen circumstances, such as a global pandemic.  We endeavor to make this decision easier by developing a model that uses mobility and customer spending data to predict the impact of closing a particular store. Here, we take the perspective of the Target Corporation with a focus on the New York metropolitan area.  Our model, which is a variation of the Huff Gravity model, will predict the customer behavior and loss of revenue that results from closing a particular store.  We consider the historical patronage data from SafeGraph for the Target stores as well as a collection of Target's competitors in the area and we combine this with demographic data from each specific census block group (CBG) to make this prediction as accurately as possible. Through this analysis, we seek to give decision makers the tool they need to make the choice easier when closing a location. </p>
    </div>
    <div class="col-2">
    </div>
  </div>
</div>
{% endblock %}

sc_proj/templates/sc_app/model.html
<!DOCTYPE html>
{% extends 'sc_app/base_fw.html' %}

{% block head_block %}
<link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock %}

{% block body_block %}
<h1>The Model</h1>
<hr class="featurette-divider">
<p style='text-indent: 50px;margin-left: 20px;margin-right: 20px;'>
{% endblock %}

sc_proj/templates/sc_app/paper.html
<!DOCTYPE html>
{% extends 'sc_app/base_fw.html' %}
{% load static %}

{% block body_block %}

<div class="container">
  <object data="{% static "pdf/temp_paper.pdf" %}" type="application/pdf" width="100%" height="1000px">
    <p>Paper - <a href="{% static "pdf/temp_paper.pdf" %}"></a></p>
  </object>
</div>


{% endblock %}

sc_proj/templates/sc_app/topStores.html
<!DOCTYPE html>
{% extends 'sc_app/base_fw.html' %}

{% block head_block %}

<script src="https://cdn.plot.ly/plotly-latest.min.js"></script>

{% endblock %}

{% block body_block %}
<div class="position-relative overflow-hidden p-3 p-md-5 m-md-3 text-center bg-light">
  <div class="col-md-5 p-lg-8 mx-auto my-5">
    <h1 class="display-6 fw-normal">Optimal Stores To Close</h1>
    <p class="lead fw-normal">The following are the top 3 stores to close according to our model.</p>
    <a class="btn btn-outline-secondary" href="{% url "sc_app:data"%}">Explore all stores</a>
  </div>
  <div class="product-device shadow-sm d-none d-md-block"></div>
  <div class="product-device product-device-2 shadow-sm d-none d-md-block"></div>
</div>
<hr class="featurette-divider">
<div class="position-relative d-md-block">
<form method="POST">
  {{ form }}
  {% csrf_token %}
  <input type="submit" class="btn btn-outline-secondary" value="Display Year">
</form>
</div>
<hr class="featurette-divider">

<div class="row featurette">
  <div class="col-md-7">
    <h2 class="featurette-heading">Optimal Store #1: <span class="text-muted">Target {{ store1 }}</span></h2>
    <strong>Closing Target {{ store1 }} results in the following movement:</strong>
    {% if tbl1 %}
    <div class='table-reponsive'>
      <table class="table table-striped">
        <thead>
          <th scope="col">Brand</th>
          <th scope="col">Address</th>
          <th scope="col">Square Footage</th>
          <th scope="col">Additional Traffic</th>
        </thead>
        {% for row in tbl1 %}
        <tr>
          <td>{{ row.brand }}</td>
          <td>{{ row.address }}</td>
          <td>{{ row.sq_ft }}</td>
          <td>{{ row.move }}</td>
        </tr>
      {% endfor %}
      </table>
      {% else %}
        <p>Select a Store.</p>
      {% endif %}
    </div>
  </div>
  <div class="col-md-5">
    {{ store_plot1 | safe }}
  </div>
</div>

<hr class="featurette-divider">

<div class="row featurette">
  <div class="col-md-7 order-md-2">
    <h2 class="featurette-heading">Optimal Store #2: <span class="text-muted">Target {{ store2 }}</span></h2>
    <strong>Closing Target {{ store2 }} results in the following movement:</strong>
    {% if tbl2 %}
    <div class='table-reponsive'>
      <table class="table table-striped">
        <thead>
          <th scope="col">Brand</th>
          <th scope="col">Address</th>
          <th scope="col">Square Footage</th>
          <th scope="col">Additional Traffic</th>
        </thead>
        {% for row in tbl2 %}
        <tr>
          <td>{{ row.brand }}</td>
          <td>{{ row.address }}</td>
          <td>{{ row.sq_ft }}</td>
          <td>{{ row.move }}</td>
        </tr>
      {% endfor %}
      </table>
      {% else %}
        <p>Select a Store.</p>
      {% endif %}
    </div>
  </div>
  <div class="col-md-5 order-md-1">
    {{ store_plot2 | safe }}
  </div>
</div>

<hr class="featurette-divider">

<div class="row featurette">
  <div class="col-md-7">
    <h2 class="featurette-heading">Optimal Store #3: <span class="text-muted"> Target {{ store3 }}</span></h2>
    <strong>Closing Target {{ store3 }} results in the following movement:</strong>
    {% if tbl3 %}
    <div class='table-reponsive'>
      <table class="table table-striped">
        <thead>
          <th scope="col">Brand</th>
          <th scope="col">Address</th>
          <th scope="col">Square Footage</th>
          <th scope="col">Additional Traffic</th>
        </thead>
        {% for row in tbl3 %}
        <tr>
          <td>{{ row.brand }}</td>
          <td>{{ row.address }}</td>
          <td>{{ row.sq_ft }}</td>
          <td>{{ row.move }}</td>
        </tr>
      {% endfor %}
      </table>
      {% else %}
        <p>Select a Store.</p>
      {% endif %}
    </div>
  </div>
  <div class="col-md-5">
    {{ store_plot3 | safe }}
  </div>
</div>

<hr class="featurette-divider">
{% endblock %}